package com.menu.demo.Controllers;
import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.menu.demo.Exceptions.ResourceNotFoundException;
import com.menu.demo.Models.SchoolAdminProfile;
import com.menu.demo.Models.User;
import com.menu.demo.Repositories.SchoolAdminProfileRepository;
import com.menu.demo.Services.ClassroomService;
import com.menu.demo.Services.SessionService;

import Dto.ClassRoomRequestDto;
import Dto.ClassRoomResponsDto;
import Dto.SessionRequestDto;
import Dto.SessionResponseDto;
import Dto.SessionUpdateDto;
import lombok.RequiredArgsConstructor;
@RestController
@RequestMapping("/api/sessions")
@RequiredArgsConstructor
public class SessionController {

    private final SessionService sessionService;
    private final SchoolAdminProfileRepository adminProfileRepository;

    // Note: sessions are auto-generated by CourseModuleService
    // this endpoint is kept for manual override if needed
    @PostMapping
    public ResponseEntity<SessionResponseDto> create(
            @RequestBody SessionRequestDto request,
            @AuthenticationPrincipal User currentUser) {
        return ResponseEntity.status(HttpStatus.CREATED)
            .body(sessionService.createSession(request, resolveAdmin(currentUser)));
    }

    // Get all non-archived sessions for a school
    @GetMapping("/school/{schoolId}")
    public ResponseEntity<List<SessionResponseDto>> getBySchool(
            @PathVariable Long schoolId) {
        return ResponseEntity.ok(sessionService.getAllSessions(schoolId));
    }

    // Update session time (with conflict check)
    @PutMapping("/{id}")
    public ResponseEntity<SessionResponseDto> update(
            @PathVariable Long id,
            @RequestBody SessionUpdateDto dto,
            @AuthenticationPrincipal User currentUser) {
        return sessionService.updateSession(id, resolveAdmin(currentUser), dto);
    }

    // Logically delete a session
    @PatchMapping("/{id}/archive")
    public ResponseEntity<SessionResponseDto> archive(
            @PathVariable Long id,
            @AuthenticationPrincipal User currentUser) {
        return sessionService.archiveSession(id, resolveAdmin(currentUser));
    }

    private SchoolAdminProfile resolveAdmin(User user) {
        return adminProfileRepository.findByUser(user)
            .orElseThrow(() -> new ResourceNotFoundException("Admin profile not found"));
    }
}