package com.menu.demo.Controllers;
import java.time.LocalDate;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.menu.demo.Exceptions.ResourceNotFoundException;
import com.menu.demo.Models.SchoolAdminProfile;
import com.menu.demo.Models.User;
import com.menu.demo.Repositories.SchoolAdminProfileRepository;
import com.menu.demo.Services.AttendenceService;
import com.menu.demo.Services.ClassroomService;
import com.menu.demo.Services.SessionService;

import Dto.AttendanceEntryDto;
import Dto.AttendanceResponseDto;
import Dto.AttendanceSheetDto;
import Dto.ClassRoomRequestDto;
import Dto.ClassRoomResponsDto;
import Dto.SessionDetailDto;
import Dto.SessionRequestDto;
import Dto.SessionResponseDto;
import Dto.SessionUpdateDto;
import Dto.WeekScheduleDto;
import lombok.RequiredArgsConstructor;
@RestController
@RequestMapping("/api/sessions")
@RequiredArgsConstructor
public class SessionController {

    private final SessionService sessionService;
    private final SchoolAdminProfileRepository adminProfileRepository;
    private final AttendenceService attendenceService;

    // Note: sessions are auto-generated by CourseModuleService
    // this endpoint is kept for manual override if needed
    @PostMapping("/{sessionId}/attendance")
    public ResponseEntity<List<AttendanceResponseDto>> markAttendance(@PathVariable Long sessionId,@RequestBody  List<AttendanceEntryDto> entries, @AuthenticationPrincipal User user){
    	return ResponseEntity.ok(attendenceService.markAttendance(sessionId,entries,resolveAdmin(user)));
    }
    @PostMapping
    public ResponseEntity<SessionResponseDto> create(
            @RequestBody SessionRequestDto request,
            @AuthenticationPrincipal User currentUser) {
        return ResponseEntity.status(HttpStatus.CREATED)
            .body(sessionService.createSession(request, resolveAdmin(currentUser)));
    }

    // Get all non-archived sessions for a school
    @GetMapping("/school/{schoolId}")
    public ResponseEntity<List<SessionResponseDto>> getBySchool(
            @PathVariable Long schoolId) {
        return ResponseEntity.ok(sessionService.getAllSessions(schoolId));
    }

    // Update session time (with conflict check)
    @PutMapping("/{id}")
    public ResponseEntity<SessionResponseDto> update(
            @PathVariable Long id,
            @RequestBody SessionUpdateDto dto,
            @AuthenticationPrincipal User currentUser) {
        return sessionService.updateSession(id, resolveAdmin(currentUser), dto);
    }

    // Logically delete a session
    @PatchMapping("/{id}/archive")
    public ResponseEntity<SessionResponseDto> archive(
            @PathVariable Long id,
            @AuthenticationPrincipal User currentUser) {
        return sessionService.archiveSession(id, resolveAdmin(currentUser));
    }
    // ── NEW: week schedule for a school ──────────────────────────
    // GET /api/sessions/week?schoolId=1&date=2025-11-07
    @GetMapping("/week")
    public ResponseEntity<WeekScheduleDto> getWeek(
            @RequestParam Long schoolId,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date) {
        return ResponseEntity.ok(sessionService.getSessionsByWeek(schoolId, date));
    }

    // ── NEW: teacher's own week schedule ─────────────────────────
    // GET /api/sessions/my-week?date=2025-11-07
    @GetMapping("/my-week")
    public ResponseEntity<WeekScheduleDto> getMyWeek(
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date,
            @AuthenticationPrincipal User currentUser) {
        return ResponseEntity.ok(sessionService.getMyWeekSchedule(currentUser, date));
    }

    // ── NEW: attendance sheet for a session (school admin) ────────
    // GET /api/sessions/5/attendance-sheet
    @GetMapping("/{sessionId}/attendance-sheet")
    public ResponseEntity<AttendanceSheetDto> getAttendanceSheet(
            @PathVariable Long sessionId,
            @AuthenticationPrincipal User currentUser) {
        return ResponseEntity.ok(
            sessionService.getAttendanceSheet(sessionId, resolveAdmin(currentUser)));
    }

    // ── NEW: attendance sheet for a session (teacher) ─────────────
    // GET /api/sessions/5/my-attendance-sheet
    @GetMapping("/{sessionId}/my-attendance-sheet")
    public ResponseEntity<AttendanceSheetDto> getAttendanceSheetForTeacher(
            @PathVariable Long sessionId,
            @AuthenticationPrincipal User currentUser) {
        return ResponseEntity.ok(
            sessionService.getAttendanceSheetForTeacher(sessionId, currentUser));
    }
    // ── NEW: sessions by date ─────────────────────────────────────
    // GET /api/sessions/by-date?schoolId=1&date=2025-11-07
    @GetMapping("/by-date")
    public ResponseEntity<List<SessionDetailDto>> getByDate(
            @RequestParam Long schoolId,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date) {
        return ResponseEntity.ok(sessionService.getSessionsByDate(schoolId, date));
    }

    private SchoolAdminProfile resolveAdmin(User user) {
        return adminProfileRepository.findByUser(user)
            .orElseThrow(() -> new ResourceNotFoundException("Admin profile not found"));
    }
}